<!DOCTYPE html>
<html>
<head>
    <title>Agent Report - {{ $agent['f_name'] }} {{ $agent['l_name'] }}</title>
    <style>
        /** Define the margins of your page **/
        @page {
            margin: 100px 25px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 0;
        }

        header {
            position: fixed;
            top: -80px;
            left: 0px;
            right: 0px;
            height: 80px;

            /** Extra personal styles **/
            text-align: center;
            line-height: 1.5;
        }

        footer {
            position: fixed; 
            bottom: -50px; 
            left: 0px; 
            right: 0px;
            height: 50px;

            /** Extra personal styles **/
            text-align: center;
            font-size: 10px;
            line-height: 1.5;
        }

        .content {
            margin-top: 0px;
            margin-bottom: 0px;
        }

        h2, h3 {
            color: #2c3e50;
            margin-bottom: 10px;
        }

        h2 {
            text-align: center;
            margin-top: 0;
        }

        h3 {
            margin-top: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 11px;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #bdc3c7;
            padding: 5px;
            text-align: left;
        }

        th {
            background-color: #f0f0f0;
            color: #2c3e50;
        }

        .summary-table td {
            border: none;
            padding: 4px 8px;
        }

        .totals-row td {
            font-weight: bold;
        }

        .badge {
            padding: 2px 4px;
            color: #fff;
            border-radius: 4px;
            font-size: 10px;
            text-align: center;
            display: inline-block;
        }

        .badge-success {
            background-color: #28a745;
        }

        .badge-danger {
            background-color: #dc3545;
        }

        .badge-warning {
            background-color: #ffc107;
            color: #212529;
        }

        .badge-info {
            background-color: #17a2b8;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .agent-info {
            margin-bottom: 20px;
        }

        /* Page number styling */
        .page-number {
            position: absolute;
            bottom: 0;
            right: 0;
            font-size: 10px;
        }

        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }

        /* Adjust header and footer line */
        hr {
            border: 0;
            border-top: 1px solid #ccc;
        }
    </style>
</head>
<body>

<!-- Header -->
<header>
    <h2>Maslink (B) Credit - Agent Report</h2>
    <p>{{ $agent['f_name'] }} {{ $agent['l_name'] }} | Date Range: {{ $reportDateRange }}</p>
    <hr>
</header>

<!-- Footer -->
<footer>
    <hr>
    <p>Generated by Sanaa Co. on {{ \Carbon\Carbon::now()->format('d M Y H:i') }}</p>
 </footer>

<div class="content">
    <!-- Agent Information -->
    <div class="agent-info">
        <p><strong>Agent:</strong> {{ $agent['f_name'] }} {{ $agent['l_name'] }}</p>
        <p><strong>Date Range:</strong> {{ $reportDateRange }}</p>
    </div>

    <!-- Summary Section -->
    <h3>Summary</h3>
    <table class="summary-table">
        <tr>
            <td><strong>Total Clients:</strong></td>
            <td>{{ $totalClients }}</td>
        </tr>
        <tr>
            <td><strong>Total Loan Amount:</strong></td>
            <td>UGX {{ number_format($totalLoanAmount, 0) }}</td>
        </tr>
        <tr>
            <td><strong>Total Collected within Date Range :</strong></td>
            <td>UGX {{ number_format($totalCollected, 0) }}</td>
        </tr>
        <tr>
            <td><strong>Total Outstanding Amount:</strong></td>
            <td>UGX {{ number_format($totalOutstandingAmount, 0) }}</td>
        </tr>
        <tr>
            <td><strong>Total Expected Payments:</strong></td>
            <td>UGX {{ number_format($totalExpectedPayments, 0) }}</td>
        </tr>
        <tr>
            <td><strong>Net Profit/Loss:</strong></td>
            <td>UGX {{ number_format($netProfitLoss, 0) }}</td>
        </tr>
        <tr>
            <td><strong>Collection Efficiency:</strong></td>
            <td>{{ number_format($collectionEfficiency, 1) }}%</td>
        </tr>
        @if($roiPercentage !== null)
        <tr>
            <td><strong>Return on Investment (ROI):</strong></td>
            <td>{{ number_format($roiPercentage,1) }}%</td>
        </tr>
        <tr>
            <td><strong>Interest Lost on Allaears:</strong></td>
            <td>{{ number_format($interestLostOnAllears,0) }}</td>
        </tr>
        <tr>
            <td><strong>Allaears  within Date range:</strong></td>
            <td>{{ number_format($allaears,0) }}</td>
        </tr>
        @endif
    </table>

    <!-- Client Payment Status Summary -->
    <h3>Client Payment Status Summary</h3>
    <table class="summary-table">
        <tr>
            <td><strong>Clients Who Paid:</strong></td>
            <td>{{ $totalClientsPaid }}</td>
        </tr>
        <tr>
            <td><strong>Clients Unpaid:</strong></td>
            <td>{{ $totalClientsUnpaid }}</td>
        </tr>
        <tr>
            <td><strong>Clients with Advance Payment:</strong></td>
            <td>{{ $totalClientsAdvancePaid }}</td>
        </tr>
        <tr>
            <td><strong>Clients with Partial Payment:</strong></td>
            <td>{{ $totalClientsPartialPaid }}</td>
        </tr>
    </table>

    <!-- Agent Expenses Section -->
    <h3>Agent Expenses</h3>
    @if(count($agentExpenses) > 0)
    <table>
        <thead>
            <tr>
                <th>Expense Description</th>
                <th class="text-right">Amount (UGX)</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($agentExpenses as $expense)
                <tr>
                    <td>{{ $expense['description'] }}</td>
                    <td class="text-right">UGX {{ number_format($expense['amount'], 0) }}</td>
                    <td>{{ \Carbon\Carbon::parse($expense['created_at'])->format('Y-m-d') }}</td>
                </tr>
            @endforeach
            <tr class="totals-row">
                <td><strong>Total Expenses:</strong></td>
                <td class="text-right">UGX {{ number_format($totalAgentExpenses, 0) }}</td>
                <td></td>
            </tr>
        </tbody>
    </table>
    @else
    <p>No expenses recorded during this period.</p>
    @endif

    <!-- Client Details Table -->
    <h3>Client Details</h3>
    <table>
        <thead>
            <tr>
                <th>Client Name</th>
                <th class="text-right">Loan Amount (UGX)</th>
                <th class="text-right">Expected Payment (UGX)</th>
                <th class="text-right">Amount Collected (UGX)</th>
                <th class="text-right">Outstanding Amount (UGX)</th>
                <th class="text-center">Payment Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($clientDetails as $client)
                <tr>
                    <td>{{ $client['name'] }}</td>
                    <td class="text-right">UGX {{ number_format($client['loan_amount'], 0) }}</td>
                    <td class="text-right">UGX {{ number_format($client['expected_payment'], 0) }}</td>
                    <td class="text-right">UGX {{ number_format($client['amount_collected'], 0) }}</td>
                    <td class="text-right">UGX {{ number_format($client['outstanding_amount'], 0) }}</td>
                    <td class="text-center">
                        <span class="badge
                            @if($client['payment_status'] == 'Paid') badge-success
                            @elseif($client['payment_status'] == 'Advance ') badge-info
                            @elseif($client['payment_status'] == 'Partial') badge-warning
                            @else badge-danger @endif">
                            {{ $client['payment_status'] }}
                        </span>
                    </td>
                </tr>
            @endforeach
            <tr class="totals-row">
                <td><strong>Totals:</strong></td>
                <td class="text-right">UGX {{ number_format($totalLoanAmount, 0) }}</td>
                <td class="text-right">UGX {{ number_format($totalExpectedPayments, 0) }}</td>
                <td class="text-right">UGX {{ number_format($totalCollected, 0) }}</td>
                <td class="text-right">UGX {{ number_format($totalOutstandingAmount, 0) }}</td>
                <td></td>
            </tr>
        </tbody>
    </table>
</div>

</body>
</html>
