<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Client Payment Statement</title>
    <style>
        body {
            font-family: "Helvetica Neue", Arial, sans-serif;
            font-size: 16px;
            color: #34495e;
            line-height: 1.6;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
        }
        .container {
            max-width: 900px;
            margin: 40px auto;
            padding: 20px;
            background-color: #ffffff;
            box-shadow: 0 6px 16px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            font-size: 28px;
            font-weight: 600;
            margin-bottom: 5px;
            color: #2c3e50;
        }
        .header p {
            font-size: 18px;
            color: #7f8c8d;
            margin: 0;
        }
        .print-button {
            text-align: right;
            margin-bottom: 20px;
        }
        .print-button button {
            background-color: #3498db;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }
        .print-button button:hover {
            background-color: #2980b9;
        }
        .section h2 {
            font-size: 22px;
            font-weight: 500;
            color: #34495e;
            border-bottom: 2px solid #ecf0f1;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #ecf0f1;
        }
        th {
            background-color: #f8f9fa;
            font-weight: 600;
            color: #34495e;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #e9f7fd;
            transition: background-color 0.3s ease;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            color: #7f8c8d;
        }
        .footer p {
            margin: 5px 0;
        }
        @media print {
            .print-button {
                display: none;
            }
            body {
                background-color: #fff;
            }
            .container {
                box-shadow: none;
                border-radius: 0;
            }
        }
    </style>
</head>
<body>

<div class="container">
    <!-- Header Section -->
    <div class="header">
        <h1>{{\App\CentralLogics\Helpers::get_business_settings('business_name')}} Services</h1>

        <h2>Client Payment Statement</h2>
        <p>Client: {{ $client->name }}</p>
        <p>Balance: UGX {{ number_format($client->credit_balance, 0) }} /=</p>
    </div>

    <!-- Print Button -->
    <div class="print-button">
        <button onclick="window.print()">Print Statement</button>
    </div>

    <!-- Payment History Section -->
    <div class="section">
        <h2>Payment History</h2>
        <table>
            <thead>
                <tr>
                    <th>Payment ID</th>
                    <th>Date</th>
                    <th>Amount (UGX)</th>
                    <th>Balance (UGX)</th>
                </tr>
            </thead>
            <tbody>
                @foreach($payments as $payment)
                    <tr>
                        <td>{{ $payment->id }}</td>
                        <td>{{ $payment->created_at->format('d M Y H:i:s') }}</td>
                        <td>{{ number_format($payment->amount, 0) }} /=</td>
                        <td>{{ number_format($payment->credit_balance, 0) }} /=</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Footer Section -->
    <div class="footer">
        <p>Thank you for choosing {{\App\CentralLogics\Helpers::get_business_settings('business_name')}} Services!</p>
        <p>Contact us: {{\App\CentralLogics\Helpers::get_business_settings('phone')}} or {{\App\CentralLogics\Helpers::get_business_settings('hotline_number')}}</p>
        <p>Generated by Sanaa | {{ \Carbon\Carbon::now()->format('F d, Y') }}</p>
  
    </div>
</div>

</body>
</html>
