<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ translate('Client Report') }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            padding-bottom: 10px;
            border-bottom: 2px solid #000;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 22px;
        }
        .header p {
            margin: 5px 0;
            font-size: 14px;
        }
        .section {
            margin-bottom: 30px;
        }
        .section h2 {
            font-size: 16px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
            margin-bottom: 15px;
            color: #2c3e50;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            font-size: 12px;
        }
        table, th, td {
            border: 1px solid #ccc;
        }
        th, td {
            padding: 6px 8px;
            text-align: left;
        }
        th {
            background-color: #f7f7f7;
            font-weight: bold;
        }
        .footer {
            position: fixed; 
            bottom: 0px; 
            left: 0px; 
            right: 0px;
            height: 50px; 
            text-align: center;
            border-top: 1px solid #000;
            padding-top: 10px;
            font-size: 10px;
            color: #555;
        }
    </style>
</head>
<body>

    <!-- Header Section -->
    <div class="header">
        <h1>{{ translate('Client Report') }}</h1>
        <p>{{ translate('Report Date') }}: {{ \Carbon\Carbon::now()->format('F d, Y') }}</p>
    </div>

    <!-- Filters Summary -->
    <div class="section">
        <h2>{{ translate('Filters Applied') }}</h2>
        <ul>
            @foreach($filters as $key => $value)
                @if($value != 'all' && !empty($value))
                    <li><strong>{{ ucfirst(str_replace('_', ' ', $key)) }}:</strong> {{ $value }}</li>
                @endif
            @endforeach
        </ul>
    </div>

    <!-- Clients Table -->
    <div class="section">
        <h2>{{ translate('Clients List') }}</h2>
        @if(!empty($clientsData) && count($clientsData) > 0)
        <table>
            <thead>
                <tr>
                    <th>{{ translate('Client Name') }}</th>
                    <th>{{ translate('Credit Balance') }}</th>
                    <th>{{ translate('Phone Number') }}</th>
                    <th>{{ translate('Agent Name') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($clientsData as $data)
                <tr>
                    <td>{{ $data['client_name'] }}</td>
                    <td>{{ number_format($data['credit_balance'], 0) }}</td>
                    <td>{{ $data['phone'] }}</td>
                    <td>{{ $data['agent_name'] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <p>{{ translate('No clients found for the selected filters.') }}</p>
        @endif
    </div>

    <div class="footer">
        <p>{{ translate('Generated by') }} Sanaa | {{ \Carbon\Carbon::now()->format('F d, Y') }}</p>
    </div>

</body>
</html>
